import { writeFileSync } from 'fs'

const lines = [
"import React, { useEffect, useState } from 'react'",
"import { useNavigate, useLocation } from 'react-router-dom'",
"import { supabase } from '../supabase'",
"",
"function Sidebar() {",
"  const navigate = useNavigate()",
"  const location = useLocation()",
"  const [profile, setProfile] = useState(null)",
"  const [projects, setProjects] = useState([])",
"  const [unreadCount, setUnreadCount] = useState(0)",
"  const [mobileOpen, setMobileOpen] = useState(false)",
"",
"  useEffect(() => {",
"    const load = async () => {",
"      const { data: { user } } = await supabase.auth.getUser()",
"      if (user) {",
"        const { data: prof } = await supabase.from('profiles').select('*').eq('id', user.id).single()",
"        setProfile(prof)",
"        const { data: proj } = await supabase.from('projects').select('*').order('created_at', { ascending: false })",
"        setProjects(proj || [])",
"        fetchUnread(user.id)",
"      }",
"    }",
"    load()",
"    setMobileOpen(false)",
"  }, [location.pathname])",
"",
"  const fetchUnread = async (userId) => {",
"    const { count } = await supabase.from('notifications').select('*', { count: 'exact', head: true }).eq('user_id', userId).eq('is_read', false)",
"    setUnreadCount(count || 0)",
"  }",
"",
"  const handleLogout = async () => {",
"    await supabase.auth.signOut()",
"    navigate('/login')",
"  }",
"",
"  const initials = profile && profile.full_name ? profile.full_name.split(' ').map(function(n) { return n[0] }).join('').toUpperCase() : '?'",
"  const colors = ['#a78bfa', '#4ade80', '#f59e0b', '#f87171', '#38bdf8']",
"",
"  const navItems = [",
"    { label: 'Dashboard', path: '/dashboard', tip: 'Overview and stats', icon: '⊞' },",
"    { label: 'Projects', path: '/projects', tip: 'All your projects', icon: '▦' },",
"    { label: 'Tasks', path: '/tasks', tip: 'Every task, filterable', icon: '✓' },",
"    { label: 'Mood board', path: '/moodboard', tip: 'Visual references', icon: '🖼' },",
"    { label: 'Activity', path: '/activity', tip: 'Team activity feed', icon: '◎' },",
"  ]",
"",
"  const sidebarContent = (",
"    React.createElement(React.Fragment, null,",
"      React.createElement('div', { style: s.logo },",
"        React.createElement('div', { style: s.logoIcon }, 'AT'),",
"        React.createElement('span', { style: s.logoText }, 'Atelier'),",
"        React.createElement('div', { style: s.mobileClose, onClick: function() { setMobileOpen(false) } }, 'x')",
"      ),",
"      React.createElement('div', { className: 'nav-row', onClick: function() { navigate('/notifications') } },",
"        React.createElement('div', { className: 'nav-item' + (location.pathname === '/notifications' ? ' nav-active' : '') },",
"          React.createElement('span', { style: { fontSize: '15px', width: '18px', textAlign: 'center' } }, '🔔'),",
"          React.createElement('span', null, 'Notifications'),",
"          unreadCount > 0 && React.createElement('span', { style: s.badge }, unreadCount),",
"          React.createElement('span', { className: 'nav-tip' }, 'See your updates')",
"        )",
"      ),",
"      React.createElement('nav', { style: s.nav },",
"        navItems.map(function(item) {",
"          return React.createElement('div', { key: item.label, className: 'nav-row', onClick: function() { navigate(item.path) } },",
"            React.createElement('div', { className: 'nav-item' + (location.pathname === item.path ? ' nav-active' : '') },",
"            React.createElement('span', { style: { fontSize: '15px', width: '18px', textAlign: 'center' } }, item.icon),",
"            React.createElement('span', null, item.label),",
"              React.createElement('span', { className: 'nav-tip' }, item.tip)",
"            )",
"          )",
"        })",
"      ),",
"      React.createElement('div', { style: s.sectionLabel }, 'Projects'),",
"      projects.slice(0, 5).map(function(p, i) {",
"        return React.createElement('div', { key: p.id, className: 'nav-row', onClick: function() { navigate('/projects/' + p.id) } },",
"          React.createElement('div', { className: 'proj-item' },",
"            React.createElement('div', { style: Object.assign({}, s.dot, { background: colors[i % colors.length] }) }),",
"            React.createElement('span', { style: s.projectName }, p.name)",
"          )",
"        )",
"      }),",
"      projects.length === 0 && React.createElement('div', { style: s.noProjects }, 'No projects yet'),",
"      React.createElement('div', { style: s.userRow },",
"        React.createElement('div', { style: s.userInfoClickable, className: 'user-info-clickable', onClick: function() { navigate('/profile') } },",
"          profile && profile.avatar_url",
"            ? React.createElement('img', { src: profile.avatar_url, alt: 'avatar', style: s.avatarImg, onError: function(e) { e.target.style.display = 'none' } })",
"            : React.createElement('div', { style: s.avatar }, initials),",
"          React.createElement('div', { style: s.userTextWrap },",
"            React.createElement('div', { style: s.userName }, profile ? profile.full_name : '...'),",
"            React.createElement('div', { style: s.userRole }, profile ? profile.role : 'member')",
"          )",
"        ),",
"        React.createElement('div', { style: s.logoutBtn, onClick: function(e) { e.stopPropagation(); handleLogout() } }, 'exit')",
"      )",
"    )",
"  )",
"",
"  return (",
"    React.createElement(React.Fragment, null,",
"      React.createElement('div', { style: s.mobileTopbar, className: 'mobile-topbar' },",
"        React.createElement('div', { style: s.mobileMenuBtn, onClick: function() { setMobileOpen(true) } },",
"          React.createElement('div', { style: s.hamburgerLine }),",
"          React.createElement('div', { style: s.hamburgerLine }),",
"          React.createElement('div', { style: s.hamburgerLine })",
"        ),",
"        React.createElement('div', { style: s.mobileLogoText }, 'Atelier'),",
"        React.createElement('div', { style: s.bellWrap, onClick: function() { navigate('/notifications') } },",
"          React.createElement('div', { style: s.bellIcon }, String.fromCodePoint(0x1F514)),",
"          unreadCount > 0 && React.createElement('div', { style: s.bellBadge }, unreadCount)",
"        )",
"      ),",
"      React.createElement('div', { style: s.sidebar, className: 'sidebar-desktop' }, sidebarContent),",
"      mobileOpen && React.createElement('div', { style: s.mobileOverlay, className: 'mobile-overlay-active', onClick: function() { setMobileOpen(false) } },",
"      React.createElement('div', { style: s.mobileSidebar, className: 'mobile-drawer', onClick: function(e) { e.stopPropagation() } }, sidebarContent)",
"      ),",
"      React.createElement('style', null, globalCss)",
"    )",
"  )",
"}",
"",
"const globalCss = [",
"'@media (max-width: 768px) { .sidebar-desktop { display: none !important; } .mobile-topbar { display: flex !important; } .mobile-overlay-active { display: flex !important; } }',",
"'.nav-row { position: relative; }',",
"'.nav-item { display: flex; align-items: center; gap: 10px; padding: 9px 16px; font-size: 13px; color: #888; cursor: pointer; transition: background 0.12s ease, color 0.12s ease, transform 0.12s ease; border-radius: 0 20px 20px 0; margin-right: 10px; position: relative; }',",
"'.nav-item:hover { background: #1c1c1c; color: #ddd; transform: translateX(2px); }',",
"'.nav-item:active { transform: translateX(2px) scale(0.97); background: #222; }',",
"'.nav-active { background: #241c3a !important; color: #a78bfa !important; font-weight: 500; }',",
"'.nav-active:hover { background: #2a2046 !important; }',",
"'.nav-tip { position: absolute; left: 100%; top: 50%; transform: translateY(-50%) scale(0.9); margin-left: 10px; background: #1f1f1f; border: 1px solid #2c2c2c; color: #ccc; font-size: 11px; padding: 5px 10px; border-radius: 6px; white-space: nowrap; opacity: 0; pointer-events: none; transition: opacity 0.15s ease, transform 0.15s ease; z-index: 10; }',",
"'.nav-item:hover .nav-tip { opacity: 1; transform: translateY(-50%) scale(1); }',",
"'@media (max-width: 768px) { .nav-tip { display: none; } }',",
"'.proj-item { display: flex; align-items: center; gap: 8px; padding: 6px 16px; cursor: pointer; border-radius: 0 20px 20px 0; margin-right: 10px; transition: background 0.12s ease; }',",
"'.proj-item:hover { background: #1c1c1c; }',",
"'.proj-item:active { background: #222; transform: scale(0.98); }',",
"'.user-info-clickable { transition: background 0.12s ease; border-radius: 8px; }',",
"'.user-info-clickable:hover { background: #1c1c1c; }',",
"'.mobile-drawer { animation: slideIn 0.25s cubic-bezier(0.32, 0.72, 0, 1); }',",
"'@keyframes slideIn { from { transform: translateX(-100%); opacity: 0.5; } to { transform: translateX(0); opacity: 1; } }',",
"].join(' ')",
"",
"const s = {",
"  mobileTopbar: { display: 'none', alignItems: 'center', justifyContent: 'space-between', padding: '14px 16px', background: '#111', borderBottom: '1px solid #1e1e1e', position: 'sticky', top: 0, zIndex: 50 },",
"  mobileMenuBtn: { display: 'flex', flexDirection: 'column', gap: '4px', cursor: 'pointer', padding: '4px' },",
"  hamburgerLine: { width: '20px', height: '2px', background: '#ccc', borderRadius: '2px' },",
"  mobileLogoText: { fontSize: '14px', fontWeight: '600', color: '#fff' },",
"  bellWrap: { position: 'relative', width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' },",
"  bellIcon: { fontSize: '16px' },",
"  bellBadge: { position: 'absolute', top: '0px', right: '0px', width: '14px', height: '14px', borderRadius: '50%', background: '#a78bfa', color: '#fff', fontSize: '8px', fontWeight: '700', display: 'flex', alignItems: 'center', justifyContent: 'center' },",
"  mobileOverlay: { display: 'none', position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', zIndex: 200 },",
"  mobileSidebar: { width: '260px', height: '100vh', background: '#111', display: 'flex', flexDirection: 'column', overflowY: 'auto' },",
"  mobileClose: { marginLeft: 'auto', color: '#666', fontSize: '14px', cursor: 'pointer', padding: '4px 8px' },",
"  sidebar: { width: '220px', background: '#111', borderRight: '1px solid #1e1e1e', display: 'flex', flexDirection: 'column', flexShrink: 0, height: '100vh', position: 'sticky', top: 0 },",
"  logo: { display: 'flex', alignItems: 'center', gap: '10px', padding: '18px 16px', borderBottom: '1px solid #1e1e1e' },",
"  logoIcon: { width: '28px', height: '28px', borderRadius: '7px', background: '#a78bfa', color: '#fff', fontWeight: '700', fontSize: '11px', display: 'flex', alignItems: 'center', justifyContent: 'center' },",
"  logoText: { fontSize: '13px', fontWeight: '600', color: '#fff' },",
"  badge: { background: '#a78bfa', color: '#fff', fontSize: '10px', fontWeight: '700', padding: '1px 7px', borderRadius: '10px', minWidth: '16px', textAlign: 'center', marginLeft: 'auto' },",
"  nav: { padding: '4px 8px 12px' },",
"  sectionLabel: { padding: '12px 16px 6px', fontSize: '10px', color: '#444', letterSpacing: '1px', textTransform: 'uppercase' },",
"  projectName: { fontSize: '12px', color: '#555', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },",
"  dot: { width: '6px', height: '6px', borderRadius: '50%', flexShrink: 0 },",
"  noProjects: { fontSize: '12px', color: '#333', padding: '6px 16px' },",
"  userRow: { display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 10px 10px 16px', marginTop: 'auto', borderTop: '1px solid #1e1e1e' },",
"  userInfoClickable: { display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer', flex: 1, minWidth: 0, padding: '4px 6px' },",
"  userTextWrap: { minWidth: 0 },",
"  avatar: { width: '30px', height: '30px', borderRadius: '50%', background: '#2d1f4e', color: '#a78bfa', fontSize: '11px', fontWeight: '700', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },",
"  avatarImg: { width: '30px', height: '30px', borderRadius: '50%', objectFit: 'cover', flexShrink: 0 },",
"  userName: { fontSize: '12px', color: '#ccc', fontWeight: '500', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },",
"  userRole: { fontSize: '11px', color: '#444', textTransform: 'capitalize' },",
"  logoutBtn: { fontSize: '11px', color: '#444', cursor: 'pointer', flexShrink: 0, padding: '4px 6px' },",
"}",
"",
"export default Sidebar",
]

writeFileSync('src/components/Sidebar.jsx', lines.join('\n'), 'utf8')
console.log('Sidebar.jsx written (profile link added)!')
