import { writeFileSync } from 'fs'

const lines = [
"import { useEffect, useState, useRef } from 'react'",
"import { useNavigate } from 'react-router-dom'",
"import { supabase } from '../supabase'",
"import Sidebar from '../components/Sidebar'",
"",
"const ROLES = ['Owner', 'Admin', 'Member']",
"",
"function Profile() {",
"  const navigate = useNavigate()",
"  const [authUser, setAuthUser] = useState(null)",
"  const [profile, setProfile] = useState(null)",
"  const [fullName, setFullName] = useState('')",
"  const [role, setRole] = useState('Member')",
"  const [avatarUrl, setAvatarUrl] = useState('')",
"  const [projectCount, setProjectCount] = useState(0)",
"  const [memberSince, setMemberSince] = useState('')",
"  const [loading, setLoading] = useState(true)",
"  const [saving, setSaving] = useState(false)",
"  const [uploading, setUploading] = useState(false)",
"  const [saved, setSaved] = useState(false)",
"  const [error, setError] = useState('')",
"  const fileInputRef = useRef(null)",
"",
"  useEffect(() => {",
"    const load = async () => {",
"      const { data: { user } } = await supabase.auth.getUser()",
"      if (!user) { setLoading(false); return }",
"      setAuthUser(user)",
"      const { data, error } = await supabase.from('profiles').select('*').eq('id', user.id).single()",
"      if (error) { setError('Could not load profile: ' + error.message) }",
"      if (data) {",
"        setProfile(data)",
"        setFullName(data.full_name || '')",
"        setRole(data.role || 'Member')",
"        setAvatarUrl(data.avatar_url || '')",
"        if (data.created_at) {",
"          setMemberSince(new Date(data.created_at).toLocaleDateString('en-IN', { month: 'short', year: 'numeric' }))",
"        }",
"      }",
"      const { count } = await supabase.from('projects').select('*', { count: 'exact', head: true })",
"      setProjectCount(count || 0)",
"      setLoading(false)",
"    }",
"    load()",
"  }, [])",
"",
"  const getInitials = (name) => name ? name.split(' ').map(n => n[0]).join('').toUpperCase() : '?'",
"",
"  const handleAvatarUpload = async (file) => {",
"    if (!authUser) return",
"    setUploading(true)",
"    setError('')",
"    const ext = file.name.split('.').pop()",
"    const fileName = authUser.id + '-' + Date.now() + '.' + ext",
"    const { error: uploadError } = await supabase.storage.from('avatars').upload(fileName, file, { upsert: true })",
"    if (uploadError) {",
"      setUploading(false)",
"      setError('Avatar upload failed: ' + uploadError.message)",
"      return",
"    }",
"    const { data: urlData } = supabase.storage.from('avatars').getPublicUrl(fileName)",
"    setAvatarUrl(urlData.publicUrl)",
"    setUploading(false)",
"  }",
"",
"  const handleSave = async () => {",
"    if (!authUser) return",
"    setSaving(true)",
"    setError('')",
"    setSaved(false)",
"    const { error: saveError } = await supabase",
"      .from('profiles')",
"      .update({ full_name: fullName.trim(), role, avatar_url: avatarUrl || null })",
"      .eq('id', authUser.id)",
"    setSaving(false)",
"    if (saveError) {",
"      setError('Could not save changes: ' + saveError.message)",
"      return",
"    }",
"    setSaved(true)",
"    setTimeout(() => setSaved(false), 2500)",
"  }",
"",
"  if (loading) {",
"    return (",
"      <div style={s.app} className='app-shell'>",
"        <Sidebar />",
"        <div style={s.main}>",
"          <div style={s.loadingText}>Loading profile...</div>",
"        </div>",
"      </div>",
"    )",
"  }",
"",
"  return (",
"    <div style={s.app} className='app-shell'>",
"      <Sidebar />",
"      <div style={s.main}>",
"        <div style={s.topbar}>",
"          <div style={s.back} onClick={() => navigate('/dashboard')}>{'\\u2039'} Dashboard</div>",
"          <div style={s.pageTitle}>Profile</div>",
"          <div style={s.pageSub}>Manage your name, role, and avatar to personalize your workspace</div>",
"        </div>",
"",
"        <div style={s.content}>",
"          <div style={s.pageBody} className='profile-body-row'>",
"            <div style={s.card}>",
"              <div style={s.avatarRow}>",
"                <div className='avatar-click-wrap' style={s.avatarWrap} onClick={() => fileInputRef.current.click()}>",
"                  {avatarUrl ? (",
"                    <img src={avatarUrl} alt='avatar' style={s.avatarImg} onError={e => { e.target.style.display = 'none' }} />",
"                  ) : (",
"                    <div style={s.avatarFallback}>{getInitials(fullName)}</div>",
"                  )}",
"                  <div className='avatar-overlay'>Edit</div>",
"                </div>",
"                <div>",
"                  <button type='button' className='avatar-upload-btn' style={s.uploadBtn} onClick={() => fileInputRef.current.click()} disabled={uploading}>",
"                    {uploading ? 'Uploading...' : 'Change avatar'}",
"                  </button>",
"                  <input ref={fileInputRef} type='file' accept='image/*' style={{ display: 'none' }} onChange={e => e.target.files[0] && handleAvatarUpload(e.target.files[0])} />",
"                  <div style={s.avatarHint}>PNG or JPG, square images look best</div>",
"                </div>",
"              </div>",
"",
"              <div style={s.fieldRow}>",
"                <div style={s.field}>",
"                  <label style={s.label}>Full name</label>",
"                  <input style={s.input} value={fullName} onChange={e => setFullName(e.target.value)} placeholder='Your name' />",
"                </div>",
"                <div style={s.field}>",
"                  <label style={s.label}>Role</label>",
"                  <select style={s.input} value={role} onChange={e => setRole(e.target.value)}>",
"                    {ROLES.map(r => <option key={r} value={r}>{r}</option>)}",
"                  </select>",
"                </div>",
"              </div>",
"",
"              <div style={s.field}>",
"                <label style={s.label}>Email</label>",
"                <div style={s.readonlyValue}>{authUser?.email || '-'}</div>",
"              </div>",
"",
"              {error && <div style={s.errorBox}>{error}</div>}",
"",
"              <div style={s.footer}>",
"                <button style={s.btnBack} onClick={() => navigate('/dashboard')}>Back to Dashboard</button>",
"                {saved && <span style={s.savedText}>Saved</span>}",
"                <button style={s.btnSave} onClick={handleSave} disabled={saving || !fullName.trim()}>",
"                  {saving ? 'Saving...' : 'Save changes'}",
"                </button>",
"              </div>",
"            </div>",
"",
"            <div style={s.sidebarCol}>",
"              <div style={s.statCard}>",
"                <div style={s.statValue}>{projectCount}</div>",
"                <div style={s.statLabel}>Active projects</div>",
"              </div>",
"              <div style={s.statCard}>",
"                <div style={s.statValue}>{memberSince || '-'}</div>",
"                <div style={s.statLabel}>Member since</div>",
"              </div>",
"              <div style={s.statCard}>",
"                <div style={s.statValueSmall}>{role}</div>",
"                <div style={s.statLabel}>Current role</div>",
"              </div>",
"            </div>",
"          </div>",
"        </div>",
"      </div>",
"",
"      <style>{css}</style>",
"    </div>",
"  )",
"}",
"",
"const css = [",
"'.avatar-click-wrap { position: relative; cursor: pointer; transition: transform 0.15s ease, box-shadow 0.15s ease; }',",
"'.avatar-click-wrap:hover { transform: scale(1.04); }',",
"'.avatar-overlay { position: absolute; inset: 0; background: rgba(0,0,0,0.55); color: #fff; font-size: 11px; font-weight: 600; letter-spacing: 0.3px; display: flex; align-items: center; justify-content: center; opacity: 0; transition: opacity 0.15s ease; border-radius: 50%; }',",
"'.avatar-click-wrap:hover .avatar-overlay { opacity: 1; }',",
"'.avatar-upload-btn { transition: background 0.15s ease, border-color 0.15s ease, transform 0.12s ease; }',",
"'.avatar-upload-btn:hover { background: #333333; border-color: #444; transform: translateY(-1px); }',",
"'.avatar-upload-btn:active { transform: translateY(0); }',",
"'@media (max-width: 900px) { .profile-body-row { flex-direction: column !important; } }',",
"].join(' ')",
"",
"const s = {",
"  app: { display: 'flex', height: '100vh', background: '#0f0f0f', color: '#fff' },",
"  main: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' },",
"  loadingText: { padding: '28px', color: '#555', fontSize: '14px' },",
"  topbar: { padding: '20px 28px', borderBottom: '1px solid #1a1a1a' },",
"  back: { fontSize: '12px', color: '#555', cursor: 'pointer', marginBottom: '6px' },",
"  pageTitle: { fontSize: '18px', fontWeight: '600', color: '#fff', marginBottom: '3px' },",
"  pageSub: { fontSize: '13px', color: '#555' },",
"  content: { flex: 1, overflowY: 'auto', padding: '28px' },",
"  pageBody: { display: 'flex', gap: '20px', alignItems: 'flex-start', maxWidth: '960px' },",
"  card: { background: '#161616', border: '1px solid #1e1e1e', borderRadius: '14px', padding: '28px', flex: '1 1 580px', minWidth: 0 },",
"  avatarRow: { display: 'flex', alignItems: 'center', gap: '20px', marginBottom: '28px' },",
"  avatarWrap: { width: '88px', height: '88px', borderRadius: '50%', overflow: 'hidden', flexShrink: 0, background: '#1e1e1e', border: '2px solid #2a2a2a' },",
"  avatarImg: { width: '100%', height: '100%', objectFit: 'cover' },",
"  avatarFallback: { width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#241c3a', color: '#a78bfa', fontSize: '26px', fontWeight: '700' },",
"  uploadBtn: { background: '#2a2a2a', color: '#ccc', border: '1px solid #333', padding: '8px 14px', borderRadius: '7px', fontSize: '12px', cursor: 'pointer' },",
"  avatarHint: { fontSize: '11px', color: '#555', marginTop: '6px' },",
"  fieldRow: { display: 'flex', gap: '16px' },",
"  field: { marginBottom: '18px', flex: 1, minWidth: 0 },",
"  label: { display: 'block', fontSize: '12px', color: '#888', marginBottom: '6px', fontWeight: '500' },",
"  input: { width: '100%', padding: '11px 14px', background: '#1e1e1e', border: '1px solid #2a2a2a', borderRadius: '8px', color: '#fff', fontSize: '14px', outline: 'none', boxSizing: 'border-box' },",
"  readonlyValue: { padding: '11px 14px', background: '#161616', border: '1px solid #222', borderRadius: '8px', color: '#666', fontSize: '14px' },",
"  errorBox: { fontSize: '12px', color: '#f87171', background: '#2a1414', border: '1px solid #3a1f1f', borderRadius: '8px', padding: '10px 12px', marginBottom: '18px' },",
"  footer: { display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: '12px', marginTop: '10px' },",
"  btnBack: { background: 'transparent', color: '#888', border: '1px solid #2a2a2a', padding: '9px 16px', borderRadius: '8px', fontSize: '13px', cursor: 'pointer', marginRight: 'auto' },",
"  savedText: { fontSize: '12px', color: '#4ade80' },",
"  btnSave: { background: '#a78bfa', color: '#fff', border: 'none', padding: '9px 18px', borderRadius: '8px', fontSize: '13px', fontWeight: '600', cursor: 'pointer' },",
"  sidebarCol: { flex: '1 1 280px', display: 'flex', flexDirection: 'column', gap: '14px', minWidth: 0 },",
"  statCard: { background: '#161616', border: '1px solid #1e1e1e', borderRadius: '12px', padding: '18px 20px' },",
"  statValue: { fontSize: '24px', fontWeight: '700', color: '#fff', marginBottom: '4px' },",
"  statValueSmall: { fontSize: '16px', fontWeight: '600', color: '#a78bfa', marginBottom: '4px' },",
"  statLabel: { fontSize: '11px', color: '#555', textTransform: 'uppercase', letterSpacing: '0.5px' },",
"}",
"",
"export default Profile",
]

writeFileSync('src/pages/Profile.jsx', lines.join('\n'), 'utf8')
console.log('Profile.jsx written (wider two-column layout + avatar/button hover animation)!')